// =============================================================
//  models/Notification.js — In-App Notification Model
//
//  Responsibilities:
//    • Store notifications generated by business events
//      (appointment booked, approved, rejected, etc.)
//    • Track read/unread state per recipient (User)
//    • Support bulk "mark all as read" operations efficiently
//    • TTL index auto-purges old read notifications after 30 days
//      to keep the collection lean
// =============================================================

const mongoose = require("mongoose");

// ── Notification type enum ───────────────────────────────────
// Kept as constants here so they can be imported by controllers.
const NOTIFICATION_TYPES = Object.freeze({
  APPOINTMENT_BOOKED:    "appointment_booked",
  APPOINTMENT_APPROVED:  "appointment_approved",
  APPOINTMENT_REJECTED:  "appointment_rejected",
  APPOINTMENT_COMPLETED: "appointment_completed",
  APPOINTMENT_CANCELLED: "appointment_cancelled",
  DOCTOR_APPROVED:       "doctor_approved",
  DOCTOR_REJECTED:       "doctor_rejected",
  GENERAL:               "general",
});

const notificationSchema = new mongoose.Schema(
  {
    // ── Recipient ─────────────────────────────────────────────
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Recipient user ID is required"],
    },

    // ── Content ───────────────────────────────────────────────
    message: {
      type: String,
      required: [true, "Notification message is required"],
      trim: true,
      maxlength: [500, "Notification message cannot exceed 500 characters"],
    },

    type: {
      type: String,
      enum: {
        values: Object.values(NOTIFICATION_TYPES),
        message: "`{VALUE}` is not a valid notification type",
      },
      default: NOTIFICATION_TYPES.GENERAL,
    },

    // Optional reference to the related document (Appointment._id, etc.)
    // Allows the frontend to build a deep-link to the relevant resource.
    relatedId: {
      type: mongoose.Schema.Types.ObjectId,
      default: null,
    },

    // ── State ─────────────────────────────────────────────────
    isRead: {
      type: Boolean,
      default: false,
    },

    // Explicit readAt timestamp (null until marked read)
    readAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true, // createdAt used for ordering & TTL
    toJSON: { versionKey: false },
    toObject: { versionKey: false },
  }
);

// ── Indexes ──────────────────────────────────────────────────

// Primary query: "Show unread notifications for user X, newest first"
notificationSchema.index({ userId: 1, isRead: 1, createdAt: -1 });

// Secondary query: all notifications for a user (notification centre)
notificationSchema.index({ userId: 1, createdAt: -1 });

// TTL index: MongoDB automatically deletes documents where
// readAt is set AND is older than 30 days.
// Unread notifications (readAt: null) are exempt from expiry.
notificationSchema.index(
  { readAt: 1 },
  {
    expireAfterSeconds: 30 * 24 * 60 * 60, // 30 days in seconds
    partialFilterExpression: { isRead: true },
    name: "ttl_read_notifications",
  }
);

// ── Pre-save hook — set readAt timestamp ────────────────────
notificationSchema.pre("save", function (next) {
  if (this.isModified("isRead") && this.isRead && !this.readAt) {
    this.readAt = new Date();
  }
  next();
});

// ── Static helpers ────────────────────────────────────────────

/**
 * Notification.createForUser
 * Convenience factory — creates and saves a single notification.
 *
 * @param {Object} params
 * @param {ObjectId} params.userId
 * @param {string}   params.message
 * @param {string}   [params.type]
 * @param {ObjectId} [params.relatedId]
 * @returns {Promise<Document>}
 */
notificationSchema.statics.createForUser = async function ({
  userId,
  message,
  type = NOTIFICATION_TYPES.GENERAL,
  relatedId = null,
}) {
  return this.create({ userId, message, type, relatedId });
};

// ── Model & constants export ──────────────────────────────────
const Notification = mongoose.model("Notification", notificationSchema);

module.exports = Notification;
module.exports.NOTIFICATION_TYPES = NOTIFICATION_TYPES;
